---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-ast
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args:
                [
                    -i,
                    --remove-all-unused-imports,
                    --ignore-init-module-imports,
                    --expand-star-imports,
                    --remove-duplicate-keys,
                ]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            files: ^api/
            args: [--settings-file, api/pyproject.toml]
    - repo: https://github.com/psf/black
      rev: 22.1.0
      hooks:
          - id: black
            files: ^api/
            language_version: python3
            args: [--config, api/pyproject.toml]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
          - id: pyupgrade
            args: [--py3-plus, --py36-plus, --py38-plus, --py39-plus, --py310-plus]

    - repo: https://github.com/pycqa/flake8
      rev: "4.0.1" # pick a git hash / tag to point to
      hooks:
          - id: flake8
            files: ^app/
            args: ["--config", "api/.flake8", "--exit-zero"] # for now
            verbose: true
            additional_dependencies:
                - flake8-eradicate
                - flake8-comprehensions
                - flake8-print
                - flake8-simplify
                - flake8-todo
