# Generated by Django 4.0.3 on 2022-03-06 02:20

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, unique=True, verbose_name="human readable task name")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.UUIDField(db_column="id", default=uuid.uuid4, primary_key=True, serialize=False)),
                ("processing_time", models.IntegerField(verbose_name="time to process")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "New"), (2, "Processing"), (3, "Completed"), (4, "Error")], default=1
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("task_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tasks.tasktype")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["-created", "status"], name="tasks_task_created_121bc1_idx"),
        ),
    ]
