# Generated by Django 4.0.3 on 2022-03-05 19:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_time_to_process_task_processing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="processing_time",
            field=models.IntegerField(verbose_name="time to process"),
        ),
    ]
